FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source
COPY . .

RUN dotnet restore "./TimeSeriesPlotter.csproj" --disable-parallel
RUN dotnet publish "./TimeSeriesPlotter.csproj" -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/sdk:8.0 
WORKDIR /app
COPY --from=build /app ./

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

RUN apt-get update && \
    apt-get install -y texlive-latex-base texlive-latex-extra 
    
ENTRYPOINT ["dotnet", "TimeSeriesPlotter.dll"]