/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataPlotForm: typeof import('./components/dataPlotForm.vue')['default']
    DataPlotGenerator: typeof import('./components/dataPlotGenerator.vue')['default']
    Editor: typeof import('./components/manim/editor.vue')['default']
    PlotDisplay: typeof import('./components/plotDisplay.vue')['default']
    PlotForm2d: typeof import('./components/plotForm2d.vue')['default']
    PlotGenerator: typeof import('./components/plotGenerator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
